version: "3.9"
services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678x@X
    # volumes:
    #   - ~/docker_backup/mongo:/data/db # /host_path:/container_path OORR volume_name:/container_path
    restart: always
    ports:
      - "27000:27017"
  shinningserver: 
    image: hungnguyen520/shinningserver:latest
    container_name: shinningserver
    environment:
      MONGO_CONN_STR: mongodb://207.148.65.86:27017/
    restart: always
    ports:
      - "9000:9900"


# docker-compose exec -T mongo sh -c 'mongodump --archive' > ~/docker_backup/mongo/db.dump
# docker-compose exec -T mongo sh -c 'mongorestore --archive' < ~/docker_backup/mongo/db.dump
# netstat -tulpn | grep LISTEN