version: "3.9"
services:
  mongo:
      image: mvertes/alpine-mongo:latest
      container_name: mongodb
      restart: always
      # command: [--auth]
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: root
      #   MONGO_INITDB_ROOT_PASSWORD: 12345678x@X
      volumes:
        - ~/docker_backup/mongo/db:/data/db # /host_path:/container_path OORR volume_name:/container_path
      ports:
      - "27017:27017"
  shinningserver: 
    image: hungnguyen520/shinningserver:latest
    container_name: shinningserver
    restart: always
    ports:
      - "9900:9900"


# docker-compose exec -T mongo sh -c 'mongodump --archive' > ~/docker_backup/mongo/db.dump
# docker-compose exec -T mongo sh -c 'mongorestore --archive' < ~/docker_backup/mongo/db.dump